# 미분

In [2]:
import torch

In [3]:
x = torch.ones(2,2,requires_grad = True) # default값은 False, True로 설정하면 x에 대해서 미분 할 수 있도록, x에 관한 연산들을 추적할 수 있게 하는 것

In [5]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [7]:
y = x+1
y       # y는 x에 대한 식이 됨, grad_function갖게 됨

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [8]:
z = 2*y**2
res = z.mean()

In [9]:
res # res를 기준으로 해서 미분하는 것

tensor(8., grad_fn=<MeanBackward0>)

In [10]:
# d(res)/dx_i = x_i + 1
# res = (z_1 + ...+z_4)/4
# z_i = 2 y_i**2
# z_i = 2(x_i+1)**2

In [11]:
res.backward() #연쇄법칙 적용

In [13]:
print(x.grad) #미분 값 보고 싶을 때

tensor([[2., 2.],
        [2., 2.]])


In [14]:
import torch.nn as nn
import torch.nn.functional as F # convolution, linear, activation function이 이미 다 만들어져 있는 library