In [1]:
# torch tensor는 numpy array와 아주 유사
import torch
import numpy as np

In [2]:
x = torch.empty(5,4)
print(x)

tensor([[1.0561e-38, 1.0653e-38, 4.1327e-39, 8.9082e-39],
        [9.8265e-39, 9.4592e-39, 1.0561e-38, 1.0929e-38],
        [1.0102e-38, 4.5918e-39, 1.0561e-38, 1.0561e-38],
        [1.0561e-38, 1.0745e-38, 1.0561e-38, 8.7245e-39],
        [9.6429e-39, 9.6429e-39, 8.7245e-39, 4.2246e-39]])


In [3]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [4]:
torch.zeros(2)

tensor([0., 0.])

In [5]:
torch.rand(5,6)

tensor([[0.9231, 0.2647, 0.7120, 0.3631, 0.8952, 0.6874],
        [0.1284, 0.3846, 0.3764, 0.5544, 0.0531, 0.3977],
        [0.8337, 0.6733, 0.4515, 0.0733, 0.1473, 0.4173],
        [0.4652, 0.3817, 0.9106, 0.4313, 0.8050, 0.1649],
        [0.2475, 0.9350, 0.9912, 0.7535, 0.3020, 0.9755]])

In [6]:
l = [13,4]
r = np.array([4,56,7])

In [7]:
# 리스트나 어레이로 되어 있으면 텐서로 변환해야함
torch.tensor(l)

tensor([13,  4])

In [8]:
torch.tensor(r)

tensor([ 4, 56,  7], dtype=torch.int32)

In [9]:
x.size()

torch.Size([5, 4])

In [10]:
type(x)

torch.Tensor

In [12]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [13]:
x

tensor([[0.2785, 0.6328],
        [0.3267, 0.6452]])

In [14]:
x+y

tensor([[0.8577, 1.3362],
        [1.1747, 1.1807]])

In [15]:
torch.add(x,y)

tensor([[0.8577, 1.3362],
        [1.1747, 1.1807]])

In [16]:
y.add(x)

tensor([[0.8577, 1.3362],
        [1.1747, 1.1807]])

In [17]:
y

tensor([[0.5791, 0.7035],
        [0.8480, 0.5355]])

# inplace방식(변수 대체)

In [18]:
y.add_(x)

tensor([[0.8577, 1.3362],
        [1.1747, 1.1807]])

In [19]:
y

tensor([[0.8577, 1.3362],
        [1.1747, 1.1807]])

In [21]:
y[1,1]

tensor(1.1807)

In [22]:
y[:,1]

tensor([1.3362, 1.1807])

# view는 사이즈를 자유롭게 바꿀 수 있다(cnn에서 flatten할 때 많이 쓴다)

In [35]:
x = torch.rand(8,8)
x

tensor([[0.5720, 0.4669, 0.8561, 0.0594, 0.5783, 0.7943, 0.2005, 0.4183],
        [0.0985, 0.1818, 0.8033, 0.5986, 0.7820, 0.3211, 0.1126, 0.9442],
        [0.3540, 0.8219, 0.0371, 0.1847, 0.8232, 0.0582, 0.2096, 0.7478],
        [0.0950, 0.4377, 0.3364, 0.2036, 0.4365, 0.6049, 0.2675, 0.1371],
        [0.4975, 0.7224, 0.5182, 0.0234, 0.2038, 0.2642, 0.5610, 0.6642],
        [0.9294, 0.1941, 0.9044, 0.2624, 0.9827, 0.4364, 0.9274, 0.5937],
        [0.5581, 0.2276, 0.4571, 0.6522, 0.2929, 0.6417, 0.7905, 0.4111],
        [0.8302, 0.9315, 0.6920, 0.7404, 0.2723, 0.9894, 0.3578, 0.3552]])

In [27]:
# 1열로 변환
x.view(64)

tensor([0.8505, 0.9470, 0.8334, 0.9264, 0.4196, 0.7598, 0.0756, 0.9020, 0.3215,
        0.0608, 0.6316, 0.4770, 0.1835, 0.9076, 0.3487, 0.7251, 0.8747, 0.3545,
        0.0143, 0.9306, 0.7208, 0.1794, 0.4011, 0.5175, 0.5143, 0.4643, 0.9951,
        0.3175, 0.9855, 0.4346, 0.5739, 0.2193, 0.8170, 0.9956, 0.8692, 0.8380,
        0.4688, 0.2219, 0.3151, 0.0755, 0.3220, 0.9182, 0.5155, 0.0266, 0.8660,
        0.1717, 0.8215, 0.1441, 0.7603, 0.5522, 0.1562, 0.7235, 0.3243, 0.7088,
        0.3410, 0.1329, 0.2715, 0.9291, 0.4334, 0.0186, 0.5027, 0.8774, 0.2229,
        0.6336])

In [28]:
x.view(4,16)

tensor([[0.8505, 0.9470, 0.8334, 0.9264, 0.4196, 0.7598, 0.0756, 0.9020, 0.3215,
         0.0608, 0.6316, 0.4770, 0.1835, 0.9076, 0.3487, 0.7251],
        [0.8747, 0.3545, 0.0143, 0.9306, 0.7208, 0.1794, 0.4011, 0.5175, 0.5143,
         0.4643, 0.9951, 0.3175, 0.9855, 0.4346, 0.5739, 0.2193],
        [0.8170, 0.9956, 0.8692, 0.8380, 0.4688, 0.2219, 0.3151, 0.0755, 0.3220,
         0.9182, 0.5155, 0.0266, 0.8660, 0.1717, 0.8215, 0.1441],
        [0.7603, 0.5522, 0.1562, 0.7235, 0.3243, 0.7088, 0.3410, 0.1329, 0.2715,
         0.9291, 0.4334, 0.0186, 0.5027, 0.8774, 0.2229, 0.6336]])

In [29]:
x.view(-1,16) # 16이 고정되어 있기 때문에 -1자리에 자동으로 4가 들어간다(나머지 값 고정되어 있어야함)

tensor([[0.8505, 0.9470, 0.8334, 0.9264, 0.4196, 0.7598, 0.0756, 0.9020, 0.3215,
         0.0608, 0.6316, 0.4770, 0.1835, 0.9076, 0.3487, 0.7251],
        [0.8747, 0.3545, 0.0143, 0.9306, 0.7208, 0.1794, 0.4011, 0.5175, 0.5143,
         0.4643, 0.9951, 0.3175, 0.9855, 0.4346, 0.5739, 0.2193],
        [0.8170, 0.9956, 0.8692, 0.8380, 0.4688, 0.2219, 0.3151, 0.0755, 0.3220,
         0.9182, 0.5155, 0.0266, 0.8660, 0.1717, 0.8215, 0.1441],
        [0.7603, 0.5522, 0.1562, 0.7235, 0.3243, 0.7088, 0.3410, 0.1329, 0.2715,
         0.9291, 0.4334, 0.0186, 0.5027, 0.8774, 0.2229, 0.6336]])

In [30]:
# tensor>>>numpy
y = x.numpy()

In [31]:
type(y) # tensor에서 numpy로 변환

numpy.ndarray

# item은 tensor가 scalar일때만 사용 가능

In [32]:
x = torch.ones(1)

In [33]:
x

tensor([1.])

In [34]:
x.item() # loss function 에서 loss값 직접 뽑아내고 싶을 때 많이 쓴다. 

1.0